# Defines PR labels and reviewers based on modified file paths.
# This is an input to the dorny/paths-filter GitHub action,
# configured to match rules if EVERY glob applies (to support exclusions).
# Use {a,b} brace groups to match any of several paths within one rule.
# Filter names are a label plus an optional comma-delimited people/teams to assign.
backend Couchers-org/backend:
  - 'app/backend/**'
  - '!app/backend/**/locales/*.json'
media Couchers-org/backend:
  - 'app/media/**'
web Couchers-org/web:
  - 'app/web/**'
  - '!app/web/**/locales/*.json'
mobile Couchers-org/mobile:
  - 'app/mobile/**'
  - '!app/mobile/**/locales/*.json'
fingerprints aapeliv:
  - 'app/mobile/fingerprint*'
locales tristanlabelle:
  - 'app/**/locales/*.json'
i18n tristanlabelle:
  - 'app/**/i18n/**'
docs aapeliv,nabramow:
  - 'docs/**'
protos:
  - 'app/proto/**'
db:
  - 'app/backend/src/couchers/{migrations,models}/**'
devops:
  - '{.github/**,**/.gitlab-ci.yml,app/docker-compose*.yml,app/deployment/**,app/{nginx,proxy,prometheus,postgis}/**}'
emails:
  - 'app/backend/templates/**'
dependencies:
  - '**/{uv.lock,yarn.lock,package-lock.json}'
