version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/app/web"
    schedule:
      interval: "weekly"
    labels:
      - "web"
      - "dependencies"
    reviewers:
      - "darrenvong"
      - "lucaslcode"

  - package-ecosystem: "pip-compile"
    directory: "/app/backend"
    schedule:
      interval: "weekly"
    labels:
      - "backend"
      - "dependencies"
    reviewers:
      - "aapeliv"

  - package-ecosystem: "pip-compile"
    directory: "/app/media"
    schedule:
      interval: "weekly"
    labels:
      - "backend"
      - "dependencies"
    reviewers:
      - "aapeliv"
