version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app/web"
    schedule:
      interval: "weekly"
    labels:
      - "web"
      - "dependencies"
    reviewers:
      - "darrenvong"
      - "lucaslcode"
