version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/app/backend"
    schedule:
      interval: "weekly"
    labels:
      - "backend"
      - "dependencies"
    reviewers:
      - "aapeliv"

  - package-ecosystem: "pip"
    directory: "/app/media"
    schedule:
      interval: "weekly"
    labels:
      - "backend"
      - "dependencies"
    reviewers:
      - "aapeliv"
