version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/app/backend"
    schedule:
      interval: "weekly"
    labels:
      - "1.topic backend"
      - "dependencies"
    reviewers:
      - "aapeliv"

  - package-ecosystem: "pip"
    directory: "/app/media"
    schedule:
      interval: "weekly"
    labels:
      - "1.topic backend"
      - "dependencies"
    reviewers:
      - "aapeliv"

  - package-ecosystem: "npm"
    directory: "/app/web"
    schedule:
      interval: "weekly"
    labels:
      - "1.topic frontend"
      - "dependencies"
    reviewers:
      - "aapeliv"
