# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Compile the protocol buffers, launch the backend with docker-compose
    before: cd app
    init: |
      docker run --rm -w /app -v $(pwd):/app couchers/grpc ./generate_protos.sh
      docker-compose up --build

  - name: Install and launch the frontend with yarn
    before: cd app/frontend
    init: yarn install
    command: REACT_APP_API_BASE_URL=$(gp url 8888) yarn start

  - name: Instructions
    before: cd app/
    init: until (curl --head -s localhost:8888 localhost:8888 > /dev/null); do sleep 1; clear; echo "Waiting for backend & frontend to come up. This might take a few minutes!"; done
    command: echo "Success! You can now launch the frontend by going to" $(gp url 3000)

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8888
