# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from pb import api_pb2 as pb_dot_api__pb2


class APIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/api.API/Ping',
                request_serializer=pb_dot_api__pb2.PingReq.SerializeToString,
                response_deserializer=pb_dot_api__pb2.PingRes.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/api.API/GetUser',
                request_serializer=pb_dot_api__pb2.GetUserReq.SerializeToString,
                response_deserializer=pb_dot_api__pb2.User.FromString,
                )
        self.UpdateProfile = channel.unary_unary(
                '/api.API/UpdateProfile',
                request_serializer=pb_dot_api__pb2.UpdateProfileReq.SerializeToString,
                response_deserializer=pb_dot_api__pb2.UpdateProfileRes.FromString,
                )
        self.SendFriendRequest = channel.unary_unary(
                '/api.API/SendFriendRequest',
                request_serializer=pb_dot_api__pb2.SendFriendRequestReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ListFriendRequests = channel.unary_unary(
                '/api.API/ListFriendRequests',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pb_dot_api__pb2.ListFriendRequestsRes.FromString,
                )
        self.ListFriends = channel.unary_unary(
                '/api.API/ListFriends',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pb_dot_api__pb2.ListFriendsRes.FromString,
                )
        self.RespondFriendRequest = channel.unary_unary(
                '/api.API/RespondFriendRequest',
                request_serializer=pb_dot_api__pb2.RespondFriendRequestReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CancelFriendRequest = channel.unary_unary(
                '/api.API/CancelFriendRequest',
                request_serializer=pb_dot_api__pb2.CancelFriendRequestReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SSO = channel.unary_unary(
                '/api.API/SSO',
                request_serializer=pb_dot_api__pb2.SSOReq.SerializeToString,
                response_deserializer=pb_dot_api__pb2.SSORes.FromString,
                )
        self.Search = channel.unary_unary(
                '/api.API/Search',
                request_serializer=pb_dot_api__pb2.SearchReq.SerializeToString,
                response_deserializer=pb_dot_api__pb2.SearchRes.FromString,
                )
        self.ListMessageThreads = channel.unary_unary(
                '/api.API/ListMessageThreads',
                request_serializer=pb_dot_api__pb2.ListMessageThreadsReq.SerializeToString,
                response_deserializer=pb_dot_api__pb2.ListMessageThreadsRes.FromString,
                )
        self.EditMessageThreadStatus = channel.unary_unary(
                '/api.API/EditMessageThreadStatus',
                request_serializer=pb_dot_api__pb2.EditMessageThreadStatusReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetMessageThread = channel.unary_unary(
                '/api.API/GetMessageThread',
                request_serializer=pb_dot_api__pb2.GetMessageThreadReq.SerializeToString,
                response_deserializer=pb_dot_api__pb2.GetMessageThreadRes.FromString,
                )
        self.GetMessageThreadInfo = channel.unary_unary(
                '/api.API/GetMessageThreadInfo',
                request_serializer=pb_dot_api__pb2.GetMessageThreadInfoReq.SerializeToString,
                response_deserializer=pb_dot_api__pb2.GetMessageThreadInfoRes.FromString,
                )
        self.CreateMessageThread = channel.unary_unary(
                '/api.API/CreateMessageThread',
                request_serializer=pb_dot_api__pb2.CreateMessageThreadReq.SerializeToString,
                response_deserializer=pb_dot_api__pb2.CreateMessageThreadRes.FromString,
                )
        self.EditMessageThread = channel.unary_unary(
                '/api.API/EditMessageThread',
                request_serializer=pb_dot_api__pb2.EditMessageThreadReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.MakeMessageThreadAdmin = channel.unary_unary(
                '/api.API/MakeMessageThreadAdmin',
                request_serializer=pb_dot_api__pb2.ThreadUserReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RemoveMessageThreadAdmin = channel.unary_unary(
                '/api.API/RemoveMessageThreadAdmin',
                request_serializer=pb_dot_api__pb2.ThreadUserReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/api.API/SendMessage',
                request_serializer=pb_dot_api__pb2.SendMessageReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.LeaveMessageThread = channel.unary_unary(
                '/api.API/LeaveMessageThread',
                request_serializer=pb_dot_api__pb2.LeaveMessageThreadReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.InviteToMessageThread = channel.unary_unary(
                '/api.API/InviteToMessageThread',
                request_serializer=pb_dot_api__pb2.ThreadUserReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SearchMessages = channel.unary_unary(
                '/api.API/SearchMessages',
                request_serializer=pb_dot_api__pb2.SearchMessagesReq.SerializeToString,
                response_deserializer=pb_dot_api__pb2.SearchMessagesRes.FromString,
                )


class APIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Pings the server for updates and basic user info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Get info about a particular user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """Update your profile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFriendRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFriendRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFriends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondFriendRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelFriendRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SSO(self, request, context):
        """Performs Discourse SSO
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search for user names and usernames (for now)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessageThreads(self, request, context):
        """Gives a paginated list of message threads with previews
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditMessageThreadStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessageThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessageThreadInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMessageThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditMessageThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeMessageThreadAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMessageThreadAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveMessageThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InviteToMessageThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=pb_dot_api__pb2.PingReq.FromString,
                    response_serializer=pb_dot_api__pb2.PingRes.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=pb_dot_api__pb2.GetUserReq.FromString,
                    response_serializer=pb_dot_api__pb2.User.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=pb_dot_api__pb2.UpdateProfileReq.FromString,
                    response_serializer=pb_dot_api__pb2.UpdateProfileRes.SerializeToString,
            ),
            'SendFriendRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFriendRequest,
                    request_deserializer=pb_dot_api__pb2.SendFriendRequestReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListFriendRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFriendRequests,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pb_dot_api__pb2.ListFriendRequestsRes.SerializeToString,
            ),
            'ListFriends': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFriends,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pb_dot_api__pb2.ListFriendsRes.SerializeToString,
            ),
            'RespondFriendRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondFriendRequest,
                    request_deserializer=pb_dot_api__pb2.RespondFriendRequestReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CancelFriendRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelFriendRequest,
                    request_deserializer=pb_dot_api__pb2.CancelFriendRequestReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SSO': grpc.unary_unary_rpc_method_handler(
                    servicer.SSO,
                    request_deserializer=pb_dot_api__pb2.SSOReq.FromString,
                    response_serializer=pb_dot_api__pb2.SSORes.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=pb_dot_api__pb2.SearchReq.FromString,
                    response_serializer=pb_dot_api__pb2.SearchRes.SerializeToString,
            ),
            'ListMessageThreads': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessageThreads,
                    request_deserializer=pb_dot_api__pb2.ListMessageThreadsReq.FromString,
                    response_serializer=pb_dot_api__pb2.ListMessageThreadsRes.SerializeToString,
            ),
            'EditMessageThreadStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.EditMessageThreadStatus,
                    request_deserializer=pb_dot_api__pb2.EditMessageThreadStatusReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMessageThread': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessageThread,
                    request_deserializer=pb_dot_api__pb2.GetMessageThreadReq.FromString,
                    response_serializer=pb_dot_api__pb2.GetMessageThreadRes.SerializeToString,
            ),
            'GetMessageThreadInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessageThreadInfo,
                    request_deserializer=pb_dot_api__pb2.GetMessageThreadInfoReq.FromString,
                    response_serializer=pb_dot_api__pb2.GetMessageThreadInfoRes.SerializeToString,
            ),
            'CreateMessageThread': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMessageThread,
                    request_deserializer=pb_dot_api__pb2.CreateMessageThreadReq.FromString,
                    response_serializer=pb_dot_api__pb2.CreateMessageThreadRes.SerializeToString,
            ),
            'EditMessageThread': grpc.unary_unary_rpc_method_handler(
                    servicer.EditMessageThread,
                    request_deserializer=pb_dot_api__pb2.EditMessageThreadReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'MakeMessageThreadAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeMessageThreadAdmin,
                    request_deserializer=pb_dot_api__pb2.ThreadUserReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveMessageThreadAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMessageThreadAdmin,
                    request_deserializer=pb_dot_api__pb2.ThreadUserReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=pb_dot_api__pb2.SendMessageReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'LeaveMessageThread': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveMessageThread,
                    request_deserializer=pb_dot_api__pb2.LeaveMessageThreadReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'InviteToMessageThread': grpc.unary_unary_rpc_method_handler(
                    servicer.InviteToMessageThread,
                    request_deserializer=pb_dot_api__pb2.ThreadUserReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SearchMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMessages,
                    request_deserializer=pb_dot_api__pb2.SearchMessagesReq.FromString,
                    response_serializer=pb_dot_api__pb2.SearchMessagesRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.API', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class API(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/Ping',
            pb_dot_api__pb2.PingReq.SerializeToString,
            pb_dot_api__pb2.PingRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/GetUser',
            pb_dot_api__pb2.GetUserReq.SerializeToString,
            pb_dot_api__pb2.User.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/UpdateProfile',
            pb_dot_api__pb2.UpdateProfileReq.SerializeToString,
            pb_dot_api__pb2.UpdateProfileRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendFriendRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/SendFriendRequest',
            pb_dot_api__pb2.SendFriendRequestReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFriendRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/ListFriendRequests',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pb_dot_api__pb2.ListFriendRequestsRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFriends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/ListFriends',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pb_dot_api__pb2.ListFriendsRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RespondFriendRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/RespondFriendRequest',
            pb_dot_api__pb2.RespondFriendRequestReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelFriendRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/CancelFriendRequest',
            pb_dot_api__pb2.CancelFriendRequestReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SSO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/SSO',
            pb_dot_api__pb2.SSOReq.SerializeToString,
            pb_dot_api__pb2.SSORes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/Search',
            pb_dot_api__pb2.SearchReq.SerializeToString,
            pb_dot_api__pb2.SearchRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListMessageThreads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/ListMessageThreads',
            pb_dot_api__pb2.ListMessageThreadsReq.SerializeToString,
            pb_dot_api__pb2.ListMessageThreadsRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditMessageThreadStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/EditMessageThreadStatus',
            pb_dot_api__pb2.EditMessageThreadStatusReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessageThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/GetMessageThread',
            pb_dot_api__pb2.GetMessageThreadReq.SerializeToString,
            pb_dot_api__pb2.GetMessageThreadRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessageThreadInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/GetMessageThreadInfo',
            pb_dot_api__pb2.GetMessageThreadInfoReq.SerializeToString,
            pb_dot_api__pb2.GetMessageThreadInfoRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateMessageThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/CreateMessageThread',
            pb_dot_api__pb2.CreateMessageThreadReq.SerializeToString,
            pb_dot_api__pb2.CreateMessageThreadRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditMessageThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/EditMessageThread',
            pb_dot_api__pb2.EditMessageThreadReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MakeMessageThreadAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/MakeMessageThreadAdmin',
            pb_dot_api__pb2.ThreadUserReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveMessageThreadAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/RemoveMessageThreadAdmin',
            pb_dot_api__pb2.ThreadUserReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/SendMessage',
            pb_dot_api__pb2.SendMessageReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LeaveMessageThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/LeaveMessageThread',
            pb_dot_api__pb2.LeaveMessageThreadReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InviteToMessageThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/InviteToMessageThread',
            pb_dot_api__pb2.ThreadUserReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.API/SearchMessages',
            pb_dot_api__pb2.SearchMessagesReq.SerializeToString,
            pb_dot_api__pb2.SearchMessagesRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
