
# Default values for deployment, this is necessary because we're using a unified helm subchart
deployment:
  # This is the name of the deployment, this is used in a _lot_ of places in the helm charts so lets just specify it
  name: app-frontend

  # For "ha" we want 2
  replicaCount: 2

  # We always only want a max of 2 pods, aka not to scale up to 3 nodes
  deploymentStrategy:
    type: Recreate
    rollingUpdate: null

  image:
    repository: 694904428454.dkr.ecr.us-east-1.amazonaws.com/web
    # If you need to debug stuff, or manually import/delete the database, uncomment these lines then kubectl exec into the pod
    # you'll also need to disable probes otherwise it will auto-restart on you
    # command: ["/bin/sh"]
    # args: ["-c", "while true; do echo hello; sleep 10;done"]

  volumeMounts:
    - name: env-volume
      mountPath: /app/.env.local
      subPath: .env
  volumes:
    - name: env-volume
      configMap:
        name: frontend-env


  # Our service listens on port 8080
  service:
    targetPort: 3000

  # livenessProbes are used to determine when to restart a container
  # Only specify the values you need to override from the defaults
  livenessProbe:
    enabled: true
    initialDelaySeconds: 480
    path: /

  # readinessProbes are used to determine when a container is ready to start accepting traffic
  # Only specify the values you need to override from the defaults
  readinessProbe:
    enabled: true
    initialDelaySeconds: 480
    path: /

  # deployment container resource requests/limits
  # this is set VERY low by default, to be aggressive above resource limiting, please override this if necessary
  # Note: Limits are HARD Limits
  #       Requests are "soft" limits and are what affects HPA (autoscaling) aggressiveness if HPA is enabled
  # resources:
  #   limits:
  #    cpu: 100m
  #    memory: 100Mi
  #   requests:
  #    cpu: 100m
  #    memory: 100Mi

  # Enable autoscaling (prod only usually, if needed)
  autoscaling:
    enabled: false

  ingress:
    enabled: true
    hosts:
      - host: REPLACE_HOSTNAME_IN_ENV_VALUES
        paths:
          - /(/+)?(.*)

  # affinity:
  #   # Every echoserver we want on a different physical node, required
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #         - key: app
  #           operator: In
  #           values:
  #           - "echoserver"
  #       topologyKey: kubernetes.io/hostname
