[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.isort]
skip_gitignore = true
include_trailing_comma = true
multi_line_output = 3
line_length = 120
