version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - cd site
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn generate-all
      - aws s3 sync dist/ s3://$BUCKET_NAME --delete --acl public-read
      - bash ./create-redirects.sh
      - echo "Done."
      - aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*"
