export const ATTENDEES = "Attendees";
export const DETAILS = "Details";
export const GOING = "Going";
export const NO_ATTENDEES = "There isn't anyone attending this event yet!";
export const NO_ORGANISERS = "There are no organisers for the event.";
export const NOT_GOING = "Not going";
export const ORGANISERS = "Organisers";
export const SEE_ALL = "See all";
export const VIRTUAL_EVENT = "Virtual event";
