export const ATTENDEES = "Attendees";
export const details = ({ colon = false }: { colon?: boolean } = {}) =>
  `Details${colon ? ":" : ""}`;
export const CREATE_EVENT = "Create event";
export const CREATE_EVENT_SUCCESS = "Event has been successfully created!";
export const END_DATE = "End date";
export const END_TIME = "End time";
export const EVENT_DETAILS = "Event details";
export const EVENT_DISCUSSION = "Event discussion";
export const EVENTS_EMPTY_STATE = "No events at the moment.";
export const EVENTS_LABEL = "Events";
export const EVENT_LINK = "Event link";
export const EVENTS_TITLE = "Events";
export const getExtraAvatarCountText = (count: number) => `+${count}`;
export const JOIN_EVENT = "Join event";
export const LEAVE_EVENT = "Leave event";
export const LOAD_MORE_ATTENDEES = "Load more attendees";
export const LOAD_MORE_ORGANISERS = "Load more organisers";
export const LOCATION = "Location";
export const NO_ATTENDEES = "There isn't anyone attending this event yet!";
export const NO_ORGANISERS = "There are no organisers for the event.";
export const ORGANISERS = "Organisers";
export const SEE_ALL = "See all";
export const SEE_MORE_EVENTS_LABEL = "See more events";
export const SHOW_ALL_EVENTS = "Show all events";
export const START_DATE = "Start date";
export const START_TIME = "Start time";
export const VIEW_DETAILS_FOR_LINK = "View details for link";
export const VIRTUAL_EVENT = "Virtual event";
export const VIRTUAL_EVENT_LINK = "Event link";
