services:
  proxy:
    build: proxy
    restart: unless-stopped
    ports:
      - 8888:8888
      #- 9901:9901
  postgres:
    image: postgis/postgis:15-3.3
    env_file: postgres.dev.env
    # uncomment this line if you want postgres to log all queries
    # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - "./data/postgres/pgdata:/var/lib/postgresql/data"
    restart: unless-stopped
    ports:
      - 6545:6545
  backend:
    build: backend
    env_file: backend.dev.env
    volumes:
      - "./backend:/app"
    # see https://github.com/eradman/entr#docker-and-windows-subsystem-for-linux
    command: bash -c "find src -name '**.py' | ENTR_INOTIFY_WORKAROUND=1 entr -rndz python src/app.py && exit 1"
    restart: unless-stopped
    ports:
      - 1751:1751
      - 1752:1752
      - 1753:1753
    depends_on:
      - postgres
    links:
      - postgres
  media:
    build: media
    restart: unless-stopped
    env_file: media.dev.env
    volumes:
      - "./data/media/uploads/:/uploads/"
    ports:
      - 5001:5001
    depends_on:
      - backend

  maildev:
    image: maildev/maildev
    restart: unless-stopped
    ports:
      - 1025:1025
      - 1080:1080

  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - "16686:16686"
    expose:
      - 4317
    environment:
      - COLLECTOR_OTLP_ENABLED=true
