# Runs all services except the backend, configuring them to talk to a backend running outside of docker.
# Use the BACKEND_HOST variable to override the address of the backend as visible from within containers.
# Run with: docker compose --file docker-compose.local-backend.yml up --build
services:
  jaeger:
    extends:
      file: docker-compose.yml
      service: jaeger
    # Make it visible to the backend outside of the container
    ports:
      - 4317:4317
  maildev:
    extends:
      file: docker-compose.yml
      service: maildev
  media:
    extends:
      file: docker-compose.yml
      service: media
    # Tell it to use the local backend
    depends_on: !reset []
    extra_hosts:
      backend: ${BACKEND_HOST:-172.17.0.1}
  proxy:
    extends:
      file: docker-compose.yml
      service: proxy
    # Tell it how to find the local backend
    extra_hosts:
      - "backend:host-gateway"
  # Not extending, because we want to build image locally, so that it buids the correct
  # image on Macs. Dockerhub has images only for x86, and they are very slow on ARM Macs.
  postgres:
    build:
      context: postgis
    env_file: postgres.dev.env
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    # to also log all queries, add: , "-c", "log_statement=all"
    volumes:
      - "./data/postgres/pgdata:/var/lib/postgresql"
    restart: unless-stopped
    ports:
      - 6545:6545
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -c 'SELECT PostGIS_Version();' || exit 1" ]
      interval: 1s
      timeout: 10s
      start_period: 5s
      retries: 10
