services:
  postgres_tests:
    image: postgis/postgis:18-3.6
    env_file: postgres.test.env
    command: postgres
      -c shared_preload_libraries=pg_stat_statements
      -c bgwriter_lru_maxpages=0
      -c jit=off
      -c fsync=off
      -c full_page_writes=off
      -c synchronous_commit=off
      -c wal_level=minimal
      -c wal_keep_size=100MB
      -c max_wal_senders=0
      # -c log_statement=all
    tmpfs: /pgdata
    restart: unless-stopped
    ports:
      - 6544:6544
    platform: linux/amd64
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -c 'SELECT PostGIS_Version();' || exit 1" ]
      interval: 1s
      timeout: 10s
      start_period: 5s
      retries: 10
  backend_test_runner:
    build: backend
    env_file: backend.test.env
    profiles: ["test"]  # This service won't start with 'up', only with 'run'
  media_tests:
    build: media
    env_file: media.test.env
    command: pytest src
    restart: unless-stopped
