syntax = "proto3";

package org.couchers.api.discussions;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

import "annotations.proto";
import "threads.proto";

service Discussions {
  option (auth_level) = AUTH_LEVEL_SECURE;

  rpc CreateDiscussion(CreateDiscussionReq) returns (Discussion) {
    // Create a new discussion
  }

  rpc GetDiscussion(GetDiscussionReq) returns (Discussion) {
    // Retrieve a discussion
  }

  rpc ListMyCommunitiesDiscussions(ListMyCommunitiesDiscussionsReq) returns (ListMyCommunitiesDiscussionsRes) {
    // List recent discussions from all communities the user belongs to, newest first
  }

  rpc UpdateDiscussion(UpdateDiscussionReq) returns (Discussion) {
    // Update a discussion; only the creator can edit
  }

  rpc DeleteDiscussion(DeleteDiscussionReq) returns (google.protobuf.Empty) {
    // Delete a discussion; creator or community moderator can delete
  }
}

message Discussion {
  int64 discussion_id = 1;
  string slug = 2;
  google.protobuf.Timestamp created = 3;
  int64 creator_user_id = 4;
  oneof owner {
    int64 owner_community_id = 5;
    int64 owner_group_id = 6;
  }
  // name of community/group that this belongs in
  string owner_title = 12;
  string title = 7;
  string content = 8;
  org.couchers.api.threads.Thread thread = 11;

  bool can_moderate = 10;
  bool can_edit = 13;
  bool deleted = 14;
  google.protobuf.Timestamp last_edited = 15;
}

message CreateDiscussionReq {
  string title = 1;
  string content = 2;
  oneof owner {
    int64 owner_community_id = 3;
    int64 owner_group_id = 4;
  }
}

message GetDiscussionReq {
  int64 discussion_id = 1;
}

message ListMyCommunitiesDiscussionsReq {
  uint32 page_size = 1;
  string page_token = 2;
}

message ListMyCommunitiesDiscussionsRes {
  repeated Discussion discussions = 1;
  string next_page_token = 2;
}

message UpdateDiscussionReq {
  int64 discussion_id = 1;
  google.protobuf.StringValue title = 2;
  google.protobuf.StringValue content = 3;
}

message DeleteDiscussionReq {
  int64 discussion_id = 1;
}
