# Justfile for the backend of the application
# Run 'just [command]' in app/backend to execute the specified command

set dotenv-load := true
set dotenv-filename := "../backend.dev.env"

DB_PASSWORD := "203d805f4b62c0a1b2f1f6b82d4583dfe563ec1619b83ce22ee414e8376a25e7"
DB_CONNECTION_STRING := "postgresql://postgres:" + DB_PASSWORD + "@localhost:6545/postgres"

# Running `just` without arguments executes this (qc stands for quality control).
[default]
qc: fmt mypy test

# Quick quality check.
qqc: fmt mypy

# Run backend locally with all needed dependencies (db etc).
run-backend:
    #!/usr/bin/env bash
    set -euo pipefail
    docker compose -f ../docker-compose.local-backend.yml up -d --build --wait
    export DATABASE_CONNECTION_STRING={{DB_CONNECTION_STRING}}
    export SMTP_HOST=localhost
    export OPENTELEMETRY_ENDPOINT=localhost:4317
    uv run src/app.py

alias rb := run-backend

# Connect to the local development database
db:
    PGPASSWORD={{DB_PASSWORD}} psql -h localhost -p 6545 -U postgres -d postgres

# Downgrade the local database to the previous migration
downgrade:
    DATABASE_CONNECTION_STRING={{DB_CONNECTION_STRING}} uv run alembic downgrade -1

# Upgrade the local database to the next migration
upgrade:
    DATABASE_CONNECTION_STRING={{DB_CONNECTION_STRING}} uv run alembic upgrade +1

# Linters.
format:
    uv run ruff check --fix . && uv run ruff format .

fmt: format

mypy:
    uv run mypy src

# Running tests.

# Start a Postgres container for backend tests
setup-test-db:
    #!/usr/bin/env bash
    set -euo pipefail
    if [[ "$(uname -s)" == "Darwin" ]]; then
        COMPOSE_FILES="-f ../docker-compose.test.yml -f ../docker-compose.testmac.yml"
    else
        COMPOSE_FILES="-f ../docker-compose.test.yml"
    fi
    docker compose $COMPOSE_FILES up -d --wait --no-deps postgres_tests
    docker compose $COMPOSE_FILES exec postgres_tests psql -U postgres -c \
        "CREATE EXTENSION IF NOT EXISTS postgis; \
         CREATE EXTENSION IF NOT EXISTS pg_trgm; \
         CREATE EXTENSION IF NOT EXISTS btree_gist"

# Tear down the test database
teardown-db:
    docker compose -f ../docker-compose.test.yml down

# Run backend tests with optional file argument
# Usage:
# just test                                → runs all tests
# just test src/tests/test_file.py         → runs tests in a specific file
test file="":
    #!/usr/bin/env bash
    just setup-test-db
    set -euo pipefail
    export DATABASE_CONNECTION_STRING=postgresql://postgres:06b3890acd2c235c41be0bbfe22f1b386a04bf02eedf8c977486355616be2aa1@localhost:6544/testdb
    uv run pytest {{ file }}
