import functools
import secrets
import string
from base64 import urlsafe_b64decode, urlsafe_b64encode

import nacl.pwhash
import nacl.utils
from google.protobuf.message import Message
from nacl.bindings import crypto_aead
from nacl.bindings.crypto_generichash import generichash_blake2b_salt_personal
from nacl.bindings.utils import sodium_memcmp
from nacl.exceptions import InvalidkeyError
from nacl.public import PrivateKey, PublicKey, SealedBox
from nacl.utils import random as random_bytes

from couchers.config import Config
from couchers.proto.internal import internal_pb2


def b64encode(data: bytes) -> str:
    return urlsafe_b64encode(data).decode("ascii")


def b64decode(data: str | bytes) -> bytes:
    return urlsafe_b64decode(data)


def b64encode_unpadded(data: bytes) -> str:
    return b64encode(data).replace("=", "")


def b64decode_unpadded(data: bytes) -> bytes:
    return b64decode(data + b"===="[len(data) % 4 :])


def _urlsafe_random_b64(length: int = 32) -> str:
    return b64encode(random_bytes(length))


def urlsafe_secure_token() -> str:
    """
    A cryptographically secure random token that can be put in a URL
    """
    return _urlsafe_random_b64(32)


def cookiesafe_secure_token() -> str:
    return random_hex(32)


def hash_password(password: str) -> bytes:
    return nacl.pwhash.str(password.encode("utf-8"))


def verify_password(hashed: bytes, password: str) -> bool:
    try:
        correct = nacl.pwhash.verify(hashed, password.encode("utf-8"))
        return correct
    except InvalidkeyError:
        return False


def random_hex(length: int = 32) -> str:
    """
    Length in binary
    """
    return random_bytes(length).hex()


def secure_compare(val1: bytes, val2: bytes) -> bool:
    return sodium_memcmp(val1, val2)


def generate_hash_signature(message: bytes, key: bytes, digest_size: int = 32) -> bytes:
    """
    Computes a blake2b keyed hash for the message.

    This can be used as a fast yet secure symmetric signature: by checking that
    the hashes agree, we can make sure the signature was generated by a party
    with knowledge of the key.
    """
    return generichash_blake2b_salt_personal(message, key=key, digest_size=digest_size)


def simple_hash_signature(message: bytes | str, key_name: str) -> str:
    if isinstance(message, str):
        msg_bytes = message.encode("utf8")
    else:
        msg_bytes = message
    return b64encode(generate_hash_signature(message=msg_bytes, key=get_secret(key_name)))


def verify_hash_signature(message: bytes, key: bytes, sig: bytes, digest_size: int = 32) -> bool:
    """
    Verifies a hash signature generated with generate_hash_signature.

    Returns true if the signature matches, otherwise false.
    """
    return secure_compare(sig, generate_hash_signature(message, key, digest_size))


def generate_random_5digit_string() -> str:
    """Return a random 5-digit string"""
    return f"{secrets.randbelow(100000):05d}"


def verify_token(a: str, b: str) -> bool:
    """Return True if strings a and b are equal, in such a way as to
    reduce the risk of timing attacks.
    """
    return secrets.compare_digest(a, b)


def stable_secure_uniform(key: bytes, seed: bytes) -> float:
    random_bytes_val = generate_hash_signature(message=seed, key=key)
    assert len(random_bytes_val) > 7
    # taken from cpython
    rr = random_bytes_val[:7]
    # Number of bits in a float
    BPF = 53
    RECIP_BPF: float = 2**-BPF
    return (int.from_bytes(rr) >> 3) * RECIP_BPF


@functools.lru_cache
def get_secret(name: str) -> bytes:
    """
    Derives a secret key from the root secret using a key derivation function
    """
    return generate_hash_signature(name.encode("utf8"), Config.current.secret)


UNSUBSCRIBE_KEY_NAME = "unsubscribe"
EMAIL_SOURCE_DATA_KEY_NAME = "email-source-data"
PAGE_TOKEN_KEY_NAME = "pagination"
SOFA_KEY_NAME = "sofa_cookie"
USER_LOCATION_RANDOMIZATION_NAME = "user-location-randomization-v1"


# AEAD: Authenticated Encryption with Associated Data

_aead_key_len = crypto_aead.crypto_aead_xchacha20poly1305_ietf_KEYBYTES
_aead_nonce_len = crypto_aead.crypto_aead_xchacha20poly1305_ietf_NPUBBYTES


def aead_generate_nonce() -> bytes:
    return random_bytes(_aead_nonce_len)


def aead_generate_key() -> bytes:
    return random_bytes(_aead_key_len)


def aead_encrypt(
    key: bytes,
    secret_data: bytes,
    plaintext_data: bytes = b"",
    nonce: bytes | None = None,
) -> tuple[bytes, bytes]:
    if not nonce:
        nonce = aead_generate_nonce()
    encrypted = crypto_aead.crypto_aead_xchacha20poly1305_ietf_encrypt(secret_data, plaintext_data, nonce, key)
    return nonce, encrypted


def aead_decrypt(key: bytes, nonce: bytes, encrypted_secret_data: bytes, plaintext_data: bytes = b"") -> bytes:
    return crypto_aead.crypto_aead_xchacha20poly1305_ietf_decrypt(encrypted_secret_data, plaintext_data, nonce, key)


def simple_encrypt(key_name: str, data: bytes) -> bytes:
    key = get_secret(key_name)
    nonce, encrypted = aead_encrypt(key, data)
    return nonce + encrypted


def simple_decrypt(key_name: str, data: bytes) -> bytes:
    key = get_secret(key_name)
    nonce, encrypted = data[:_aead_nonce_len], data[_aead_nonce_len:]
    return aead_decrypt(key, nonce, encrypted)


def encrypt_proto(key_name: str, message: Message) -> str:
    """
    Encrypts a protobuf message and returns a base64-encoded string.
    """
    return b64encode(simple_encrypt(key_name, message.SerializeToString()))


def decrypt_proto[T: Message](key_name: str, encrypted_value: str, proto_class: type[T]) -> T:
    """
    Decrypts a base64-encoded string and parses it as the given proto class.
    Raises an exception if decryption or parsing fails.
    """
    return proto_class.FromString(simple_decrypt(key_name, b64decode(encrypted_value)))


_sofa_sig_len = 16
_sofa_id_len = 18


def create_sofa_id() -> bytes:
    return random_bytes(_sofa_id_len)


def encode_sofa(sofa_id: bytes, payload: internal_pb2.SofaPayload) -> str:
    serialized = payload.SerializeToString()
    sig = generate_hash_signature(sofa_id + serialized, get_secret(SOFA_KEY_NAME), digest_size=_sofa_sig_len)
    return b64encode(sofa_id + serialized + sig)


def decode_sofa(signed_value: str) -> tuple[bytes, internal_pb2.SofaPayload]:
    data = b64decode(signed_value)
    if len(data) < _sofa_id_len + _sofa_sig_len:
        raise ValueError("Invalid signed data: too short")
    if not verify_hash_signature(
        data[:-_sofa_sig_len], get_secret(SOFA_KEY_NAME), data[-_sofa_sig_len:], digest_size=_sofa_sig_len
    ):
        raise ValueError("Invalid signature")
    return data[:_sofa_id_len], internal_pb2.SofaPayload.FromString(data[_sofa_id_len:-_sofa_sig_len])


def encrypt_page_token(plaintext_page_token: str) -> str:
    return b64encode(simple_encrypt(PAGE_TOKEN_KEY_NAME, plaintext_page_token.encode("utf8")))


def decrypt_page_token(encrypted_page_token: str) -> str:
    return simple_decrypt(PAGE_TOKEN_KEY_NAME, b64decode(encrypted_page_token)).decode("utf8")


# Public key cryptography


def asym_encrypt(public_key: bytes, data: bytes) -> bytes:
    return SealedBox(PublicKey(public_key)).encrypt(data)


def asym_decrypt(private_key: bytes, encrypted_data: bytes) -> bytes:
    return SealedBox(PrivateKey(private_key)).decrypt(encrypted_data)


def generate_asym_keypair() -> tuple[bytes, bytes]:
    skey = PrivateKey.generate()
    return skey.encode(), skey.public_key.encode()


def generate_invite_code(length: int = 8) -> str:
    """
    Generates a secure, URL-safe invite code of the given length.
    """
    alphabet = string.ascii_lowercase + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))
