import io
import json
from base64 import urlsafe_b64encode
from concurrent import futures
from contextlib import contextmanager
from datetime import UTC, datetime, timedelta
from pathlib import Path
from urllib.parse import urlencode

import exifread
import grpc
import pytest
import pyvips
from google.protobuf import empty_pb2
from google.protobuf.timestamp_pb2 import Timestamp
from nacl.bindings.crypto_generichash import generichash_blake2b_salt_personal
from nacl.utils import random as random_bytes
from PIL import ExifTags, Image
from PIL.JpegImagePlugin import JpegImageFile
from PIL.TiffImagePlugin import IFDRational

from media.proto import media_pb2, media_pb2_grpc
from media.server import create_app

DATADIR = Path(__file__).parent / "data"


class MockMainServer(media_pb2_grpc.MediaServicer):
    def __init__(self, bearer_token, accept_func):
        self._bearer_token = bearer_token
        self._accept_func = accept_func
        self.requests = []

    def UploadConfirmation(self, request, context):
        self.requests.append(request)
        metadata = dict(context.invocation_metadata())
        if (
            "authorization" not in metadata
            or not metadata["authorization"].startswith("Bearer ")
            or metadata["authorization"][7:] != self._bearer_token
        ):
            context.abort(grpc.StatusCode.UNAUTHENTICATED, "Unauthorized")

        if self._accept_func(request):
            return empty_pb2.Empty()
        else:
            raise Exception("Didn't accept")


@contextmanager
def mock_main_server(*args, **kwargs):
    server = grpc.server(futures.ThreadPoolExecutor(1))
    server.add_secure_port("localhost:8088", grpc.local_server_credentials())
    servicer = MockMainServer(*args, **kwargs)
    media_pb2_grpc.add_MediaServicer_to_server(servicer, server)
    server.start()

    try:
        yield servicer
    finally:
        server.stop(None).wait()


@pytest.fixture
def client_with_secrets(tmp_path):
    secret_key = random_bytes(32)
    bearer_token = random_bytes(32).hex()

    app = create_app(
        media_server_secret_key=secret_key,
        media_server_bearer_token=bearer_token,
        media_server_base_url="https://testing.couchers.invalid",
        main_server_address="localhost:8088",
        main_server_use_ssl=False,
        media_upload_location=tmp_path,
        media_cors_origin="*",
        thumbnail_size=200,
    )

    with app.test_client() as client:
        yield client, secret_key, bearer_token


def Timestamp_from_datetime(dt: datetime):
    pb_ts = Timestamp()
    pb_ts.FromDatetime(dt)
    return pb_ts


def generate_hash_signature(message: bytes, key: bytes) -> bytes:
    """
    Computes a blake2b keyed hash for the message.

    This can be used as a fast yet secure symmetric signature: by checking that
    the hashes agree, we can make sure the signature was generated by a party
    with knowledge of the key.
    """
    return generichash_blake2b_salt_personal(message, key=key, digest_size=32)


def generate_upload_path(request, media_server_secret_key):
    req = request.SerializeToString()
    data = urlsafe_b64encode(req).decode("utf8")
    sig = urlsafe_b64encode(generate_hash_signature(req, media_server_secret_key)).decode("utf8")

    return "upload?" + urlencode({"data": data, "sig": sig})


def test_index(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets
    rv = client.get("/")
    assert b"404" in rv.data


def test_robots(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets
    rv = client.get("/robots.txt")
    assert rv.data == b"User-agent: *\nDisallow: /\n"
    assert rv.mimetype == "text/plain"


def create_upload_request():
    key = random_bytes(32).hex()

    now = datetime.now(UTC)
    expiry = now + timedelta(minutes=20)

    return key, media_pb2.UploadRequest(
        key=key,
        type=media_pb2.UploadRequest.UploadType.IMAGE,
        created=Timestamp_from_datetime(now),
        expiry=Timestamp_from_datetime(expiry),
        max_width=2000,
        max_height=1600,
    )


def test_image_upload(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "1x1.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "1x1.jpg")})

        jd = json.loads(rv.data)
        assert jd["ok"]
        assert jd["key"] == key
        assert jd["filename"] == f"{key}.jpg"
        assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
        assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"


def test_image_resizing(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "5000x5000.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "img.jpg")})

        jd = json.loads(rv.data)
        assert jd["ok"]
        assert jd["key"] == key
        assert jd["filename"] == f"{key}.jpg"
        assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
        assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"

        rv = client.get(f"/img/full/{key}.jpg")
        assert rv.status_code == 200

        img = Image.open(io.BytesIO(rv.data))

        assert img.width <= 2000
        assert img.height <= 1600

        assert img.width == 2000 or img.height == 1600


def test_thumbnail_downscaling(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "5000x5000.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "img.jpg")})

        jd = json.loads(rv.data)
        assert jd["ok"]
        assert jd["key"] == key
        assert jd["filename"] == f"{key}.jpg"
        assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
        assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"

        rv = client.get(f"/img/thumbnail/{key}.jpg")
        assert rv.status_code == 200

        img = Image.open(io.BytesIO(rv.data))

        assert img.width == 200
        assert img.height == 200


def test_thumbnail_downscaling_wide(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "5000x1000.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "img.jpg")})

        jd = json.loads(rv.data)
        assert jd["ok"]
        assert jd["key"] == key
        assert jd["filename"] == f"{key}.jpg"
        assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
        assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"

        rv = client.get(f"/img/thumbnail/{key}.jpg")
        assert rv.status_code == 200

        img = Image.open(io.BytesIO(rv.data))

        assert img.width == 200
        assert img.height == 200


def test_thumbnail_downscaling_tall(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "1000x5000.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "img.jpg")})

        jd = json.loads(rv.data)
        assert jd["ok"]
        assert jd["key"] == key
        assert jd["filename"] == f"{key}.jpg"
        assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
        assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"

        rv = client.get(f"/img/thumbnail/{key}.jpg")
        assert rv.status_code == 200

        img = Image.open(io.BytesIO(rv.data))

        assert img.width == 200
        assert img.height == 200


def test_thumbnail_upscaling(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "1x1.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "img.jpg")})

        jd = json.loads(rv.data)
        assert jd["ok"]
        assert jd["key"] == key
        assert jd["filename"] == f"{key}.jpg"
        assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
        assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"

        rv = client.get(f"/img/thumbnail/{key}.jpg")
        assert rv.status_code == 200

        img = Image.open(io.BytesIO(rv.data))

        assert img.width == 200
        assert img.height == 200


def is_our_pixel(img_bytes):
    img = Image.open(io.BytesIO(img_bytes))

    if not isinstance(img, JpegImageFile):
        return False

    if img.width != 1:
        return False

    if img.height != 1:
        return False

    if img.convert("RGB").getpixel((0, 0)) != (100, 47, 115):
        return False

    return True


def test_upload_broken_sig(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    upload_path = "upload?data=krz&sig=foo"

    rv = client.post(upload_path, data={"file": (io.BytesIO(b"bar"), "1x1.jpg")})

    assert rv.status_code == 400


def test_wrong_filename(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "1x1.jpg", "rb") as f:
            # filename shouldn't matter
            rv = client.post(upload_path, data={"file": (f, "wrongname.exe")})

        jd = json.loads(rv.data)
        assert jd["ok"]
        assert jd["key"] == key
        assert jd["filename"] == f"{key}.jpg"
        assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
        assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"

        rv = client.get(f"/img/full/{key}.jpg")
        assert rv.status_code == 200

        assert is_our_pixel(rv.data)


def test_strips_exif(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True) as main_server:
        img = Image.open(DATADIR / "exif.jpg")
        assert img.getexif()
        assert img.info["comment"] == b"I am an EXIF comment!\0"

        with open(DATADIR / "exif.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "1x1.jpg")})

        jd = json.loads(rv.data)
        assert jd["ok"]
        assert jd["key"] == key
        assert jd["filename"] == f"{key}.jpg"
        assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
        assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"

        rv = client.get(f"/img/full/{key}.jpg")
        assert rv.status_code == 200

        img = Image.open(io.BytesIO(rv.data))
        assert "comment" not in img.info
        assert not img.getexif()

        metadata = main_server.requests[0].metadata
        assert metadata.exif
        assert metadata.xmp
        assert metadata.iptc


def test_jpg_pixel(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "1x1.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "pixel")})

        jd = json.loads(rv.data)
        assert jd["ok"]
        assert jd["key"] == key
        assert jd["filename"] == f"{key}.jpg"
        assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
        assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"

        rv = client.get(f"/img/full/{key}.jpg")
        assert rv.status_code == 200

        assert is_our_pixel(rv.data)


def test_png_pixel(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "1x1.png", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "pixel")})

        jd = json.loads(rv.data)
        assert jd["ok"]
        assert jd["key"] == key
        assert jd["filename"] == f"{key}.jpg"
        assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
        assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"

        rv = client.get(f"/img/full/{key}.jpg")
        assert rv.status_code == 200

        assert is_our_pixel(rv.data)


def test_gif_pixel(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "1x1.gif", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "pixel")})

        jd = json.loads(rv.data)
        assert jd["ok"]
        assert jd["key"] == key
        assert jd["filename"] == f"{key}.jpg"
        assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
        assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"

        rv = client.get(f"/img/full/{key}.jpg")
        assert rv.status_code == 200

        assert is_our_pixel(rv.data)


def test_bad_file(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "badfile.txt", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "badfile.txt")})

        assert rv.status_code == 400


def test_cant_reuse(client_with_secrets):
    # can't reuse the same signed request
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "1x1.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "pixel.jpg")})

        jd = json.loads(rv.data)
        assert jd["ok"]
        assert jd["key"] == key
        assert jd["filename"] == f"{key}.jpg"
        assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
        assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"

        rv = client.get(f"/img/full/{key}.jpg")
        assert rv.status_code == 200

        with open(DATADIR / "1x1.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "pixel.jpg")})

        assert rv.status_code == 400


def test_fails_wrong_sig(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    wrong_secret_key = random_bytes(32)

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, wrong_secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "1x1.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "pixel.jpg")})

        assert rv.status_code == 400


def test_fails_expired(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key = random_bytes(32).hex()

    now = datetime.now(UTC)
    created = now - timedelta(minutes=12)
    expiry = now - timedelta(minutes=2)

    request = media_pb2.UploadRequest(
        key=key,
        type=media_pb2.UploadRequest.UploadType.IMAGE,
        created=Timestamp_from_datetime(created),
        expiry=Timestamp_from_datetime(expiry),
        max_width=2000,
        max_height=1600,
    )

    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "1x1.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "pixel.jpg")})

        assert rv.status_code == 400


def test_cors_header_set_on_all_responses(client_with_secrets):
    # a cross-origin response without ACAO is treated as a network error by
    # browsers, so the header must be present on error responses too
    client, secret_key, bearer_token = client_with_secrets

    # success
    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True):
        with open(DATADIR / "1x1.jpg", "rb") as f:
            rv = client.post(upload_path, data={"file": (f, "1x1.jpg")})

    assert rv.status_code == 200
    assert rv.headers["Access-Control-Allow-Origin"] == "*"

    # broken signature
    rv = client.post("upload?data=krz&sig=foo", data={"file": (io.BytesIO(b"bar"), "1x1.jpg")})
    assert rv.status_code == 400
    assert rv.headers["Access-Control-Allow-Origin"] == "*"

    # invalid image
    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with open(DATADIR / "badfile.txt", "rb") as f:
        rv = client.post(upload_path, data={"file": (f, "badfile.txt")})

    assert rv.status_code == 400
    assert rv.headers["Access-Control-Allow-Origin"] == "*"

    # missing file
    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    rv = client.post(upload_path)
    assert rv.status_code == 400
    assert rv.headers["Access-Control-Allow-Origin"] == "*"


def one_pixel_bytes():
    """Get a simple 1x1 pixel gif image as a sequence of bytes"""
    gif = io.BytesIO()
    Image.frombytes("P", (1, 1), b"\0").save(gif, format="gif")
    return gif.getvalue()


def test_cache_headers(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    f = io.BytesIO(one_pixel_bytes())

    with mock_main_server(bearer_token, lambda x: True):
        rv = client.post(upload_path, data={"file": (f, "f")})
    assert rv.status_code == 200
    jd = json.loads(rv.data)

    assert jd["ok"]
    assert jd["key"] == key
    assert jd["filename"] == f"{key}.jpg"
    assert jd["full_url"] == f"https://testing.couchers.invalid/img/full/{key}.jpg"
    assert jd["thumbnail_url"] == f"https://testing.couchers.invalid/img/thumbnail/{key}.jpg"

    rv = client.get(f"/img/full/{key}.jpg")
    assert rv.status_code == 200
    assert "max-age=7776000" in rv.headers["Cache-Control"].split(", ")
    assert "Expires" in rv.headers
    assert "Etag" in rv.headers
    etag = rv.headers["Etag"]

    # Test with matching Etag
    rv = client.get(f"/img/full/{key}.jpg", headers=[("If-None-Match", etag)])
    assert rv.status_code == 304  # Not Modified

    # Test with mismatching Etag
    rv = client.get(f"/img/full/{key}.jpg", headers=[("If-None-Match", "strunt")])
    assert rv.status_code == 200


def exif_source_bytes():
    with open(DATADIR / "exif.jpg", "rb") as f:
        return f.read()


def upload_and_confirm(client, secret_key, bearer_token, image_bytes, filename="img"):
    key, request = create_upload_request()
    upload_path = generate_upload_path(request, secret_key)

    with mock_main_server(bearer_token, lambda x: True) as main_server:
        rv = client.post(upload_path, data={"file": (io.BytesIO(image_bytes), filename)})
        assert rv.status_code == 200
        assert json.loads(rv.data)["ok"]

        assert len(main_server.requests) == 1
        return main_server.requests[0]


def test_metadata_segments_shipped_verbatim(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    source = exif_source_bytes()
    metadata = upload_and_confirm(client, secret_key, bearer_token, source).metadata

    assert metadata.exif.startswith(b"Exif\0\0")
    for segment in (metadata.exif, metadata.xmp, metadata.iptc):
        assert segment in source


def test_metadata_parsed_view(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    metadata = upload_and_confirm(client, secret_key, bearer_token, exif_source_bytes()).metadata
    parsed = json.loads(metadata.parsed_json)

    assert parsed["Image Software"] == "GIMP 2.10.14"
    assert parsed["Image DateTime"] == "2020:08:13 10:01:50"
    assert parsed["EXIF UserComment"] == "I am an EXIF comment!"
    assert "\0" not in metadata.parsed_json


def test_metadata_gps_parsed(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    img = Image.new("RGB", (4, 4), (10, 20, 30))
    exif = Image.Exif()
    exif[ExifTags.Base.Make] = "TestCam"
    exif[ExifTags.IFD.GPSInfo] = {
        ExifTags.GPS.GPSLatitudeRef: "N",
        ExifTags.GPS.GPSLatitude: (IFDRational(60), IFDRational(10), IFDRational(2550, 100)),
        ExifTags.GPS.GPSLongitudeRef: "E",
        ExifTags.GPS.GPSLongitude: (IFDRational(24), IFDRational(56), IFDRational(1200, 100)),
    }
    buf = io.BytesIO()
    img.save(buf, format="jpeg", exif=exif)

    metadata = upload_and_confirm(client, secret_key, bearer_token, buf.getvalue()).metadata
    parsed = json.loads(metadata.parsed_json)

    assert parsed["Image Make"] == "TestCam"
    assert parsed["GPS GPSLatitudeRef"] == "N"
    assert parsed["GPS GPSLatitude"] == "[60, 10, 51/2]"
    assert parsed["GPS GPSLongitudeRef"] == "E"
    assert parsed["GPS GPSLongitude"] == "[24, 56, 12]"


def test_parsed_view_excludes_thumbnail_blob(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    source = exif_source_bytes()
    thumbnail = bytes(pyvips.Image.new_from_buffer(source, options="").get("jpeg-thumbnail-data"))
    metadata = upload_and_confirm(client, secret_key, bearer_token, source).metadata

    assert "JPEGThumbnail" not in metadata.parsed_json
    assert len(metadata.parsed_json) < len(thumbnail)


def test_no_embedded_metadata_for_bare_image(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    with open(DATADIR / "1x1.png", "rb") as f:
        metadata = upload_and_confirm(client, secret_key, bearer_token, f.read()).metadata

    assert not metadata.exif
    assert not metadata.xmp
    assert not metadata.iptc
    assert not metadata.parsed_json
    assert not metadata.parse_error
    assert metadata.original_format == "png"


def test_embedded_thumbnail_rides_inside_exif(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    source = exif_source_bytes()
    thumbnail = bytes(pyvips.Image.new_from_buffer(source, options="").get("jpeg-thumbnail-data"))
    assert thumbnail

    metadata = upload_and_confirm(client, secret_key, bearer_token, source).metadata

    assert thumbnail in metadata.exif
    parsed = json.loads(metadata.parsed_json)
    assert parsed["Thumbnail ImageWidth"] == "256"
    assert parsed["Thumbnail JPEGInterchangeFormatLength"] == str(len(thumbnail))


def test_catalog_records_the_original_file(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    with open(DATADIR / "5000x1000.jpg", "rb") as f:
        source = f.read()

    metadata = upload_and_confirm(client, secret_key, bearer_token, source, filename="DSC_0001.JPG").metadata

    assert metadata.original_filename == "DSC_0001.JPG"
    assert metadata.original_format == "jpeg"
    assert metadata.original_size == len(source)
    assert metadata.original_width == 5000
    assert metadata.original_height == 1000


@pytest.mark.parametrize("name,expected", [("1x1.jpg", "jpeg"), ("1x1.png", "png"), ("1x1.gif", "gif")])
def test_catalog_format_per_container(client_with_secrets, name, expected):
    client, secret_key, bearer_token = client_with_secrets

    with open(DATADIR / name, "rb") as f:
        metadata = upload_and_confirm(client, secret_key, bearer_token, f.read()).metadata

    assert metadata.original_format == expected


def test_catalog_filename_is_recorded_but_never_used_as_a_path(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    with open(DATADIR / "1x1.jpg", "rb") as f:
        source = f.read()

    name = "../../etc/passwd.jpg"
    request = upload_and_confirm(client, secret_key, bearer_token, source, filename=name)

    assert request.metadata.original_filename == name
    assert request.filename == f"{request.key}.jpg"


def test_webp_exif_is_kept_raw_even_though_the_parse_misses_it(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    img = Image.new("RGB", (4, 4), (10, 20, 30))
    exif = Image.Exif()
    exif[ExifTags.Base.Make] = "TestCam"
    buf = io.BytesIO()
    img.save(buf, format="webp", exif=exif)

    metadata = upload_and_confirm(client, secret_key, bearer_token, buf.getvalue()).metadata

    assert metadata.original_format == "webp"
    assert b"TestCam" in metadata.exif
    assert not metadata.parsed_json
    assert not metadata.parse_error


def test_heif_metadata_is_captured_raw(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    with open(DATADIR / "exif.avif", "rb") as f:
        source = f.read()

    metadata = upload_and_confirm(client, secret_key, bearer_token, source, filename="IMG_1234.HEIC").metadata

    assert metadata.original_format == "heif"
    assert metadata.original_filename == "IMG_1234.HEIC"
    assert metadata.original_width == 120
    assert metadata.original_height == 90
    assert metadata.exif.startswith(b"Exif\0\0")
    assert b"iPhone 15 Pro" in metadata.exif
    assert b"Apple" in metadata.exif


def test_a_raising_parser_does_not_fail_the_upload(client_with_secrets):
    client, secret_key, bearer_token = client_with_secrets

    with open(DATADIR / "exif.avif", "rb") as f:
        source = f.read()

    with pytest.raises(AssertionError):
        exifread.process_file(io.BytesIO(source), extract_thumbnail=False)

    metadata = upload_and_confirm(client, secret_key, bearer_token, source).metadata

    assert not metadata.parsed_json
    assert b"iPhone 15 Pro" in metadata.exif

    assert metadata.parse_error.startswith("Traceback")
    assert "exifread/core/heic.py" in metadata.parse_error
    assert metadata.parse_error.rstrip().endswith("AssertionError")
