# Set up all of the CI env vars required for Couchers
runs:
  using: "composite"
  steps:
    # Get clean environment variables via https://github.com/marketplace/actions/github-environment-variables-action
    - uses: FranzDiebold/github-env-vars-action@v2
    - shell: bash
      run: |
        echo "SLUG=CI_SHA" >> $GITHUB_ENV
