server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    http2 on;

    server_name {WEB_DOMAIN};

    access_log /var/log/nginx/{WEB_DOMAIN}.access.log;
    error_log /var/log/nginx/{WEB_DOMAIN}.error.log;

    ssl_certificate /certs/live/{WEB_DOMAIN}/fullchain.pem;
    ssl_certificate_key /certs/live/{WEB_DOMAIN}/privkey.pem;

    location /api/ {
        proxy_set_header x-couchers-real-ip $remote_addr;

        proxy_http_version 1.1;
        proxy_pass http://envoy:8888/;
    }

    location / {
        proxy_http_version 1.1;
        proxy_pass http://web:3000;
    }

    # Proxy requests to Sentry to avoid ad blockers.
    location /sentry-tunnel/ {
      # Remove /sentry-tunnel/ prefix and keep the rest of the path
      rewrite ^/sentry-tunnel/(.*) /$1 break;

      # This token is already exposed on the frontend, and Sentry docs mention that
      # it's fine to expose it.
      proxy_pass https://5594adb1a53e41bfbb9f2cc5c91e2dbd@o782870.ingest.sentry.io;
      proxy_set_header Host o782870.ingest.sentry.io;
      proxy_set_header X-Real-IP $remote_addr;

      # Standard proxy headers (optional but recommended)
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # SSL configuration for upstream
      proxy_ssl_server_name on;
  }
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    http2 on;
    server_name {WEB_DOMAIN};
    return 301 https://$host$request_uri;
}
