
# Default values for deployment, this is necessary because we're using a unified helm subchart
statefulset:
  # This is the name of the deployment, this is used in a _lot_ of places in the helm charts so lets just specify it
  name: app-media

  # For "ha" we want 2
  replicaCount: 1

  # We always only want a max of 2 pods, aka not to scale up to 3 nodes
  deploymentStrategy:
    type: Recreate
    rollingUpdate: null

  image:
    repository: 694904428454.dkr.ecr.us-east-1.amazonaws.com/media
    # If you need to debug stuff, or manually import/delete the database, uncomment these lines then kubectl exec into the pod
    # you'll also need to disable probes otherwise it will auto-restart on you
    # command: ["/bin/sh"]
    # args: ["-c", "while true; do echo hello; sleep 10;done"]

  # Our service listens on port 8080
  service:
    targetPort: 5000

  # livenessProbes are used to determine when to restart a container
  # Only specify the values you need to override from the defaults
  livenessProbe:
    probeType: tcpSocket
    port: 5000

  # readinessProbes are used to determine when a container is ready to start accepting traffic
  # Only specify the values you need to override from the defaults
  readinessProbe:
    probeType: tcpSocket
    port: 5000


  persistence:
    enabled: true
    size: 5Gi
    path: "/uploads"
    storageClass: "gp3-retain"
  # deployment container resource requests/limits
  # this is set VERY low by default, to be aggressive above resource limiting, please override this if necessary
  # Note: Limits are HARD Limits
  #       Requests are "soft" limits and are what affects HPA (autoscaling) aggressiveness if HPA is enabled
  resources:
    limits:
     cpu: 100m
     memory: 100Mi
    requests:
     cpu: 100m
     memory: 100Mi

  # Enable autoscaling (prod only usually, if needed)
  autoscaling:
    enabled: false

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Referer,Accept,X-Auth-Token
    hosts:
      - host: REPLACE_HOSTNAME_IN_ENV_VALUES
        paths:
          - /(/+)?(.*)

  # affinity:
  #   # Every echoserver we want on a different physical node, required
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #         - key: app
  #           operator: In
  #           values:
  #           - "echoserver"
  #       topologyKey: kubernetes.io/hostname
