backend:
  name: github
  branch: develop
  repo: couchers-org/couchers
media_folder: app/web/public/img
public_folder: /img
publish_mode: editorial_workflow
display_url: https://couchers.org
logo_url: https://app.couchers.org/logo512.png
collections:
  - label: "Blog"
    name: "blog"
    folder: "app/web/markdown/blog"
    path: "{{year}}/{{month}}/{{day}}/{{slug}}"
    slug: "{{slug}}"
    create: true
    nested:
      depth: 100
    fields:
      - label: Title
        name: title
        widget: string
      - label: Slug
        name: slug
        widget: string
        hint: The slug is used in the URL of the post
      - label: Description
        name: description
        widget: string
        hint: SEO description
      - label: Date
        name: date
        widget: date
        format: YYYY/MM/DD
        hint: Publish date
      - label: Author
        name: author
        widget: string
        hint: First name of author, e.g. "Aapeli"
      - label: Share Image
        name: share_image
        widget: image
        allow_multiple: false
        media_folder: /app/web/public/img/blog
        hint: SEO image
      - label: Content
        name: body
        widget: markdown

  - label: "Issues"
    name: "issues"
    folder: "app/web/markdown"
    nested:
      depth: 100
    filter: { field: "type", value: "issue" }
    create: false
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
        required: false
      - label: Breadcrumb label
        name: crumb
        widget: string
        hint: Override the navigation crumb above the title
        required: false
      - label: Bustitle
        name: bustitle
        widget: string
        hint: Text shown at the end of the post to link to a "plan" page
        required: false
      - label: Content
        name: body
        widget: markdown

  - label: "Plan"
    name: "plan"
    folder: "app/web/markdown"
    nested:
      depth: 100
    filter: { field: "type", value: "plan" }
    create: false
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
        required: false
      - label: Breadcrumb label
        name: crumb
        widget: string
        hint: Override the navigation crumb above the title
        required: false
      - label: Subtitle
        name: subtitle
        widget: string
        hint: Text shown at the start of the post to link to an "issue" page
        required: false
      - label: Content
        name: body
        widget: markdown

  - label: "Other pages"
    name: "general"
    folder: "app/web/markdown"
    nested:
      depth: 100
    filter: { field: "type", value: "general" }
    create: false
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
        required: false
      - label: Breadcrumb label
        name: crumb
        widget: string
        hint: Override the navigation crumb above the title
        required: false
      - label: Content
        name: body
        widget: markdown
