#!/usr/bin/env node
// Computes Expo fingerprints for our release variants and either checks them
// against the repo's fingerprints file or writes the new values to it.
//
// The fingerprint is the runtimeVersion that Expo stamps into a native binary;
// an OTA bundle only applies when its runtimeVersion matches the installed
// build. We pin the fingerprints in app/mobile/fingerprints so every branch's
// CI can detect when a change has moved them — that is the signal that a new
// store build needs to be cut (which happens only on develop).
//
// File format: a leading comment block plus one line per entry of the form
//   variant/platform=hash
// chosen so the build scripts can read it with `grep | cut` and so a single
// fingerprint change is a one-line diff.
//
// Usage:
//   node scripts/fingerprints.mjs check   # fail if computed != committed
//   node scripts/fingerprints.mjs write   # update the fingerprints file
//
// Run from app/mobile.

import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const FILE = resolve(HERE, "..", "fingerprints");
const VARIANTS = ["devtool", "staging", "production"];
const PLATFORMS = ["ios", "android"];

const HEADER = [
  "# Fingerprints (Expo runtimeVersion) for each release variant × platform.",
  "# Generated by: cd app/mobile && npm run fingerprints:write",
  "# Verified on every branch by the test:mobile-fingerprints CI job; a",
  "# mismatch with what `npx expo-updates fingerprint:generate` produces means",
  "# a native change has moved the fingerprint and a fresh store build will be",
  "# needed when merged to develop.",
].join("\n");

function compute(variant, platform) {
  const r = spawnSync(
    "npx",
    ["expo-updates", "fingerprint:generate", "--platform", platform],
    {
      env: { ...process.env, APP_VARIANT: variant },
      encoding: "utf-8",
    },
  );
  if (r.status !== 0) {
    process.stderr.write(r.stderr ?? "");
    throw new Error(`fingerprint:generate failed for ${variant}/${platform}`);
  }
  const json = JSON.parse(r.stdout);
  if (!json.hash) {
    throw new Error(
      `fingerprint:generate did not return a hash for ${variant}/${platform}`,
    );
  }
  return json.hash;
}

function computeAll() {
  const out = {};
  for (const v of VARIANTS) {
    for (const p of PLATFORMS) {
      process.stderr.write(`computing fingerprint for ${v}/${p}…\n`);
      out[`${v}/${p}`] = compute(v, p);
    }
  }
  return out;
}

function readCommitted() {
  if (!existsSync(FILE)) return null;
  const out = {};
  for (const raw of readFileSync(FILE, "utf-8").split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    out[line.slice(0, eq)] = line.slice(eq + 1);
  }
  return out;
}

function serialize(actual) {
  const lines = [HEADER];
  for (const v of VARIANTS) {
    for (const p of PLATFORMS) {
      lines.push(`${v}/${p}=${actual[`${v}/${p}`]}`);
    }
  }
  return lines.join("\n") + "\n";
}

function diff(actual, committed) {
  const out = [];
  for (const v of VARIANTS) {
    for (const p of PLATFORMS) {
      const key = `${v}/${p}`;
      const c = committed?.[key];
      const a = actual[key];
      if (c !== a) out.push({ key, expected: c, actual: a });
    }
  }
  return out;
}

const mode = process.argv[2];

if (mode === "check") {
  const committed = readCommitted();
  if (!committed) {
    process.stderr.write(
      `No fingerprints file found at ${FILE}.\n` +
        `Run \`npm run fingerprints:write\` (in app/mobile) to create it.\n`,
    );
    process.exit(1);
  }
  const actual = computeAll();
  const mismatches = diff(actual, committed);
  if (mismatches.length === 0) {
    process.stdout.write("Fingerprints match.\n");
    process.exit(0);
  }
  process.stderr.write(
    "Fingerprint mismatch — native-affecting change(s) detected:\n\n",
  );
  for (const m of mismatches) {
    process.stderr.write(`  ${m.key}:\n`);
    process.stderr.write(`    committed: ${m.expected ?? "(missing)"}\n`);
    process.stderr.write(`    computed:  ${m.actual}\n`);
  }
  process.stderr.write(
    "\nIf you intentionally made a native-affecting change, run:\n" +
      "  (cd app/mobile && npm run fingerprints:write)\n" +
      "and commit the updated fingerprints file. Merging it to develop will\n" +
      "trigger a new store build.\n\n" +
      "If you didn't intend to change native behavior, revisit your change —\n" +
      "something in it moved the runtimeVersion.\n",
  );
  process.exit(1);
} else if (mode === "write") {
  const actual = computeAll();
  writeFileSync(FILE, serialize(actual));
  process.stdout.write(`Wrote ${FILE}\n`);
} else {
  process.stderr.write("Usage: node scripts/fingerprints.mjs <check|write>\n");
  process.exit(2);
}
