"""Add language table

Revision ID: 0a4fb7fcb678
Revises: 8b6297128973
Create Date: 2021-01-17 10:33:14.483955

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0a4fb7fcb678'
down_revision = '8b6297128973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_abilities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=3), nullable=False),
    sa.Column('fluency', sa.Enum('fluency_unspecified', 'fluency_say_hello', 'fluency_beginner', 'fluency_intermediate', 'fluency_advanced', 'fluency_fluent', 'fluency_native', name='fluency'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_language_abilities_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_language_abilities'))
    )
    op.create_index(op.f('ix_language_abilities_user_id'), 'language_abilities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_abilities_user_id'), table_name='language_abilities')
    op.drop_table('language_abilities')
    # ### end Alembic commands ###
