"""Add index on background jobs

Revision ID: 13fe6ada1535
Revises: e54417789a02
Create Date: 2022-02-10 16:45:08.181199

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "13fe6ada1535"
down_revision = "e54417789a02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_background_jobs_state_next_attempt_after", "background_jobs", ["state", "next_attempt_after"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_background_jobs_state_next_attempt_after", table_name="background_jobs")
    # ### end Alembic commands ###
