"""Adding region tables

Revision ID: 2b6848de3679
Revises: 8445d5383ddc
Create Date: 2021-03-31 04:10:09.601296

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2b6848de3679"
down_revision = "8445d5383ddc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions_lived",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("region_code", sa.String(length=3), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_regions_lived_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions_lived")),
        sa.UniqueConstraint("user_id", "region_code", name=op.f("uq_regions_lived_user_id")),
    )
    op.create_index(op.f("ix_regions_lived_user_id"), "regions_lived", ["user_id"], unique=False)
    op.create_table(
        "regions_visited",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("region_code", sa.String(length=3), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_regions_visited_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions_visited")),
        sa.UniqueConstraint("user_id", "region_code", name=op.f("uq_regions_visited_user_id")),
    )
    op.create_index(op.f("ix_regions_visited_user_id"), "regions_visited", ["user_id"], unique=False)
    op.drop_column("users", "countries_visited")
    op.drop_column("users", "countries_lived")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("countries_lived", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("users", sa.Column("countries_visited", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_regions_visited_user_id"), table_name="regions_visited")
    op.drop_table("regions_visited")
    op.drop_index(op.f("ix_regions_lived_user_id"), table_name="regions_lived")
    op.drop_table("regions_lived")
    # ### end Alembic commands ###
