"""Add location fields

Revision ID: 398ef021e653
Revises: 3c0f67ff3ea2
Create Date: 2020-10-23 17:14:18.918433

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "398ef021e653"
down_revision = "3c0f67ff3ea2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(geometry_type="POINT", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
    )
    op.add_column("users", sa.Column("geom_radius", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "geom_radius")
    op.drop_column("users", "geom")
    # ### end Alembic commands ###
