"""Add thread ids and remove title from thread

Revision ID: 40eed876879e
Revises: 20b0d7fd2619
Create Date: 2021-02-06 12:00:22.997662

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "40eed876879e"
down_revision = "20b0d7fd2619"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clusters", sa.Column("thread_id", sa.BigInteger(), nullable=False))
    op.create_unique_constraint(op.f("uq_clusters_thread_id"), "clusters", ["thread_id"])
    op.create_foreign_key(op.f("fk_clusters_thread_id_threads"), "clusters", "threads", ["thread_id"], ["id"])
    op.create_unique_constraint(op.f("uq_discussions_thread_id"), "discussions", ["thread_id"])
    op.drop_index("ix_discussions_thread_id", table_name="discussions")
    op.create_unique_constraint(op.f("uq_events_thread_id"), "events", ["thread_id"])
    op.drop_index("ix_events_thread_id", table_name="events")
    op.alter_column("pages", "thread_id", existing_type=sa.BIGINT(), nullable=False)
    op.create_unique_constraint(op.f("uq_pages_thread_id"), "pages", ["thread_id"])
    op.drop_index("ix_pages_thread_id", table_name="pages")
    op.drop_column("threads", "title")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("threads", sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index("ix_pages_thread_id", "pages", ["thread_id"], unique=True)
    op.drop_constraint(op.f("uq_pages_thread_id"), "pages", type_="unique")
    op.alter_column("pages", "thread_id", existing_type=sa.BIGINT(), nullable=True)
    op.create_index("ix_events_thread_id", "events", ["thread_id"], unique=True)
    op.drop_constraint(op.f("uq_events_thread_id"), "events", type_="unique")
    op.create_index("ix_discussions_thread_id", "discussions", ["thread_id"], unique=True)
    op.drop_constraint(op.f("uq_discussions_thread_id"), "discussions", type_="unique")
    op.drop_constraint(op.f("fk_clusters_thread_id_threads"), "clusters", type_="foreignkey")
    op.drop_constraint(op.f("uq_clusters_thread_id"), "clusters", type_="unique")
    op.drop_column("clusters", "thread_id")
    # ### end Alembic commands ###
