"""TEMP: regions

Revision ID: 4d25e0913b95
Revises: e624769ebede
Create Date: 2020-12-26 15:07:39.848796

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d25e0913b95"
down_revision = "e624769ebede"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("alpha3", sa.String(length=3), nullable=False),
        sa.Column("alpha2", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("wikidata_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("alpha3", name=op.f("pk_regions")),
        sa.UniqueConstraint("alpha2", name=op.f("uq_regions_alpha2")),
        sa.UniqueConstraint("name", name=op.f("uq_regions_name")),
    )
    op.create_table(
        "region_polygons",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("alpha3", sa.String(length=3), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=False,
        ),
        sa.Column("admin_level", sa.SmallInteger(), nullable=True),
        sa.Column("area", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["alpha3"], ["regions.alpha3"], name=op.f("fk_region_polygons_alpha3_regions")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_region_polygons")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("region_polygons")
    op.drop_table("regions")
    # ### end Alembic commands ###
