"""Renaming countries to regions

Revision ID: 75b3e461565e
Revises: 8445d5383ddc
Create Date: 2021-03-30 23:23:24.877307

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "75b3e461565e"
down_revision = "8445d5383ddc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("regions_lived", sa.String(), nullable=True))
    op.add_column("users", sa.Column("regions_visited", sa.String(), nullable=True))
    op.drop_column("users", "countries_lived")
    op.drop_column("users", "countries_visited")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("countries_visited", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("users", sa.Column("countries_lived", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("users", "regions_visited")
    op.drop_column("users", "regions_lived")
    # ### end Alembic commands ###
