"""Adding token to user model

Revision ID: 847768bd3b9c
Revises: 27a2782784d0
Create Date: 2021-04-09 14:36:35.178872

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "847768bd3b9c"
down_revision = "27a2782784d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("old_email_token", sa.String(), nullable=True))
    op.add_column("users", sa.Column("old_email_token_created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("old_email_token_expiry", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "old_email_token_expiry")
    op.drop_column("users", "old_email_token_created")
    op.drop_column("users", "old_email_token")
    # ### end Alembic commands ###
