"""Add foreign key indexes

Revision ID: 8b6297128973
Revises: 34cb1d27d207
Create Date: 2020-12-18 19:07:38.467667

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b6297128973"
down_revision = "34cb1d27d207"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_complaints_author_user_id"), "complaints", ["author_user_id"], unique=False)
    op.create_index(op.f("ix_complaints_reported_user_id"), "complaints", ["reported_user_id"], unique=False)
    op.create_index(
        op.f("ix_friend_relationships_from_user_id"), "friend_relationships", ["from_user_id"], unique=False
    )
    op.create_index(op.f("ix_friend_relationships_to_user_id"), "friend_relationships", ["to_user_id"], unique=False)
    op.create_index(
        op.f("ix_group_chat_subscriptions_group_chat_id"), "group_chat_subscriptions", ["group_chat_id"], unique=False
    )
    op.create_index(op.f("ix_group_chat_subscriptions_user_id"), "group_chat_subscriptions", ["user_id"], unique=False)
    op.create_index(op.f("ix_group_chats_creator_id"), "group_chats", ["creator_id"], unique=False)
    op.create_index(op.f("ix_host_requests_from_user_id"), "host_requests", ["from_user_id"], unique=False)
    op.create_index(op.f("ix_host_requests_to_user_id"), "host_requests", ["to_user_id"], unique=False)
    op.create_index(op.f("ix_initiated_uploads_user_id"), "initiated_uploads", ["user_id"], unique=False)
    op.create_index(op.f("ix_login_tokens_user_id"), "login_tokens", ["user_id"], unique=False)
    op.create_index(op.f("ix_messages_author_id"), "messages", ["author_id"], unique=False)
    op.create_index(op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_messages_target_id"), "messages", ["target_id"], unique=False)
    op.create_index(op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False)
    op.create_index(op.f("ix_references_from_user_id"), "references", ["from_user_id"], unique=False)
    op.create_index(op.f("ix_references_to_user_id"), "references", ["to_user_id"], unique=False)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_references_to_user_id"), table_name="references")
    op.drop_index(op.f("ix_references_from_user_id"), table_name="references")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_messages_target_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_author_id"), table_name="messages")
    op.drop_index(op.f("ix_login_tokens_user_id"), table_name="login_tokens")
    op.drop_index(op.f("ix_initiated_uploads_user_id"), table_name="initiated_uploads")
    op.drop_index(op.f("ix_host_requests_to_user_id"), table_name="host_requests")
    op.drop_index(op.f("ix_host_requests_from_user_id"), table_name="host_requests")
    op.drop_index(op.f("ix_group_chats_creator_id"), table_name="group_chats")
    op.drop_index(op.f("ix_group_chat_subscriptions_user_id"), table_name="group_chat_subscriptions")
    op.drop_index(op.f("ix_group_chat_subscriptions_group_chat_id"), table_name="group_chat_subscriptions")
    op.drop_index(op.f("ix_friend_relationships_to_user_id"), table_name="friend_relationships")
    op.drop_index(op.f("ix_friend_relationships_from_user_id"), table_name="friend_relationships")
    op.drop_index(op.f("ix_complaints_reported_user_id"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_author_user_id"), table_name="complaints")
    # ### end Alembic commands ###
