"""Added Host Request Reminders

Revision ID: 8c7b607d948c
Revises: a0d344cfb455
Create Date: 2025-04-29 01:55:59.214122

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8c7b607d948c"
down_revision = "a0d344cfb455"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE notificationtopicaction ADD VALUE 'host_request__reminder'")
    op.add_column(
        "host_requests",
        sa.Column("host_sent_request_reminders", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "host_requests",
        sa.Column("last_sent_request_reminder_time", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_host_pending_requests", "host_requests", [sa.text("(status = 'pending')")], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_host_pending_requests", table_name="host_requests")
    op.drop_column("host_requests", "last_sent_request_reminder_time")
    op.drop_column("host_requests", "host_sent_request_reminders")
    # ### end Alembic commands ###
