"""Upgrade to latest

Revision ID: 939e33415d86
Revises: 406fcdd10a2b
Create Date: 2020-09-29 13:14:17.528115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939e33415d86'
down_revision = '406fcdd10a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # alembic is dumb
    message_type = sa.Enum('text', 'chat_created', 'chat_edited', 'user_invited', 'user_left', 'user_made_admin', 'user_removed_admin', name='messagetype')
    message_type.create(op.get_bind())
    op.add_column('messages', sa.Column('message_type', message_type, nullable=False, server_default='text'))
    # drop default
    op.alter_column('messages', 'message_type', server_default=None)

    op.add_column('messages', sa.Column('target_id', sa.Integer(), nullable=True))
    op.alter_column('messages', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'messages', 'users', ['target_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('messages', 'target_id')
    op.drop_column('messages', 'message_type')
    # ### end Alembic commands ###
