"""Add page parent

Revision ID: 93bda1361f40
Revises: 83e5a560bba3
Create Date: 2021-02-13 17:20:28.345698

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "93bda1361f40"
down_revision = "83e5a560bba3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pages", sa.Column("parent_node_id", sa.BigInteger(), nullable=False))
    op.create_index(op.f("ix_pages_parent_node_id"), "pages", ["parent_node_id"], unique=False)
    op.create_foreign_key(op.f("fk_pages_parent_node_id_nodes"), "pages", "nodes", ["parent_node_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_pages_parent_node_id_nodes"), "pages", type_="foreignkey")
    op.drop_index(op.f("ix_pages_parent_node_id"), table_name="pages")
    op.drop_column("pages", "parent_node_id")
    # ### end Alembic commands ###
