"""Add account management fields

Revision ID: aef55e9fa4a9
Revises: 51398a87b2ef
Create Date: 2020-12-02 10:18:41.253310

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aef55e9fa4a9"
down_revision = "51398a87b2ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_tokens",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expiry", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_password_reset_tokens_user_id_users")),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_password_reset_tokens")),
    )
    op.add_column("users", sa.Column("new_email", sa.String(), nullable=True))
    op.add_column("users", sa.Column("new_email_token", sa.String(), nullable=True))
    op.add_column("users", sa.Column("new_email_token_created", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("new_email_token_expiry", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "new_email_token_expiry")
    op.drop_column("users", "new_email_token_created")
    op.drop_column("users", "new_email_token")
    op.drop_column("users", "new_email")
    op.drop_table("password_reset_tokens")
    # ### end Alembic commands ###
