"""Adding is_deleted

Revision ID: b4645870f298
Revises: 02eda17d1e9b
Create Date: 2021-02-28 04:09:39.510975

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b4645870f298"
down_revision = "02eda17d1e9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_deleted")
    # ### end Alembic commands ###
