"""Adding is_deleted

Revision ID: d09b671bccce
Revises: 17362f602f12
Create Date: 2021-03-04 01:12:14.125624

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d09b671bccce"
down_revision = "17362f602f12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_deleted")
    # ### end Alembic commands ###
