"""TEMP: land_polygons

Revision ID: e624769ebede
Revises: a7ce4cb0a7f0
Create Date: 2020-12-25 18:12:32.744133

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e624769ebede"
down_revision = "a7ce4cb0a7f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "land_polygons",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("x", sa.SmallInteger(), nullable=True),
        sa.Column("y", sa.SmallInteger(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON", srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_land_polygons")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("land_polygons")
    # ### end Alembic commands ###
