"""Add enhanced session fields

Revision ID: f85e551b9334
Revises: 8e790df2a689
Create Date: 2020-12-07 10:03:21.194156

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f85e551b9334"
down_revision = "8e790df2a689"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("api_calls", sa.Integer(), nullable=False))
    op.add_column(
        "sessions", sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column("sessions", sa.Column("deleted", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "sessions",
        sa.Column(
            "expiry", sa.DateTime(timezone=True), server_default=sa.text("now() + interval '7 days'"), nullable=False
        ),
    )
    op.add_column("sessions", sa.Column("ip_address", sa.String(), nullable=True))
    op.add_column(
        "sessions", sa.Column("last_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column("sessions", sa.Column("long_lived", sa.Boolean(), nullable=False))
    op.add_column("sessions", sa.Column("user_agent", sa.String(), nullable=True))
    op.drop_column("sessions", "started")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "started",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("sessions", "user_agent")
    op.drop_column("sessions", "long_lived")
    op.drop_column("sessions", "last_seen")
    op.drop_column("sessions", "ip_address")
    op.drop_column("sessions", "expiry")
    op.drop_column("sessions", "deleted")
    op.drop_column("sessions", "created")
    op.drop_column("sessions", "api_calls")
    # ### end Alembic commands ###
