# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from pb import bugs_pb2 as pb_dot_bugs__pb2


class BugsStub(object):
    """This is an open service, no authentication is needed
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Version = channel.unary_unary(
                '/org.couchers.bugs.Bugs/Version',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pb_dot_bugs__pb2.VersionInfo.FromString,
                )
        self.ReportBug = channel.unary_unary(
                '/org.couchers.bugs.Bugs/ReportBug',
                request_serializer=pb_dot_bugs__pb2.ReportBugReq.SerializeToString,
                response_deserializer=pb_dot_bugs__pb2.ReportBugRes.FromString,
                )


class BugsServicer(object):
    """This is an open service, no authentication is needed
    """

    def Version(self, request, context):
        """Returns backend version info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportBug(self, request, context):
        """Report a bug
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BugsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pb_dot_bugs__pb2.VersionInfo.SerializeToString,
            ),
            'ReportBug': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportBug,
                    request_deserializer=pb_dot_bugs__pb2.ReportBugReq.FromString,
                    response_serializer=pb_dot_bugs__pb2.ReportBugRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.couchers.bugs.Bugs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bugs(object):
    """This is an open service, no authentication is needed
    """

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.couchers.bugs.Bugs/Version',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pb_dot_bugs__pb2.VersionInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportBug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.couchers.bugs.Bugs/ReportBug',
            pb_dot_bugs__pb2.ReportBugReq.SerializeToString,
            pb_dot_bugs__pb2.ReportBugRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
