# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from pb import jail_pb2 as pb_dot_jail__pb2


class JailStub(object):
    """This is a secure service but allows jailed users access.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JailInfo = channel.unary_unary(
                '/org.couchers.jail.Jail/JailInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pb_dot_jail__pb2.JailInfoRes.FromString,
                )
        self.AcceptTOS = channel.unary_unary(
                '/org.couchers.jail.Jail/AcceptTOS',
                request_serializer=pb_dot_jail__pb2.AcceptTOSReq.SerializeToString,
                response_deserializer=pb_dot_jail__pb2.JailInfoRes.FromString,
                )
        self.SetLocation = channel.unary_unary(
                '/org.couchers.jail.Jail/SetLocation',
                request_serializer=pb_dot_jail__pb2.SetLocationReq.SerializeToString,
                response_deserializer=pb_dot_jail__pb2.JailInfoRes.FromString,
                )


class JailServicer(object):
    """This is a secure service but allows jailed users access.
    """

    def JailInfo(self, request, context):
        """
        Jail API

        If the user hasn't completed necessary steps needed to use the app, they are
        only allowed to hit the Jail API.

        E.g. if signing up is incomplete, or they haven't agreed to TOS, etc.

        These API functions are available only to signed-in users, but while other
        APIs can't be used while Jailed, these can.
        Get reason why the user is in jail, e.g. hasn't completed all sign-up
        steps, or needs to read something, etc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptTOS(self, request, context):
        """Accept to TOS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLocation(self, request, context):
        """Set the user's location
        If you're not jailed, do this with api.UpdateProfile!
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JailServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JailInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.JailInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pb_dot_jail__pb2.JailInfoRes.SerializeToString,
            ),
            'AcceptTOS': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptTOS,
                    request_deserializer=pb_dot_jail__pb2.AcceptTOSReq.FromString,
                    response_serializer=pb_dot_jail__pb2.JailInfoRes.SerializeToString,
            ),
            'SetLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLocation,
                    request_deserializer=pb_dot_jail__pb2.SetLocationReq.FromString,
                    response_serializer=pb_dot_jail__pb2.JailInfoRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.couchers.jail.Jail', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Jail(object):
    """This is a secure service but allows jailed users access.
    """

    @staticmethod
    def JailInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.couchers.jail.Jail/JailInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pb_dot_jail__pb2.JailInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcceptTOS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.couchers.jail.Jail/AcceptTOS',
            pb_dot_jail__pb2.AcceptTOSReq.SerializeToString,
            pb_dot_jail__pb2.JailInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.couchers.jail.Jail/SetLocation',
            pb_dot_jail__pb2.SetLocationReq.SerializeToString,
            pb_dot_jail__pb2.JailInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
