FROM node:20-bullseye AS builder

ARG environment=development
WORKDIR /app

# disable next.js telemetry
ENV NEXT_TELEMETRY_DISABLED=1

ARG version
ENV NEXT_PUBLIC_VERSION=$version
ENV SENTRY_RELEASE=$version

ARG display_version
ENV NEXT_PUBLIC_DISPLAY_VERSION=$display_version

ARG commit_sha
ENV NEXT_PUBLIC_COMMIT_SHA=$commit_sha

ARG commit_timestamp
ENV NEXT_PUBLIC_COMMIT_TIMESTAMP=$commit_timestamp

COPY package.json yarn.lock ./

RUN corepack enable
RUN yarn install --immutable

COPY . .

RUN cp .env.$environment env && \
    rm .env.* && \
    mv env .env.local

RUN if [ "$environment" = "production" ]; then cp public/robots-prod.txt public/robots.txt; fi

RUN yarn build

RUN yarn injectsourcemaps

FROM node:20-slim AS runner

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

COPY --from=builder /app/.env.local ./
COPY --from=builder /app/proto ./proto


EXPOSE 3000

ENV HOSTNAME="::"

CMD ["node", "server.js"]
