build:docs:
  stage: build
  image: python:3.12-bullseye
  inherit:
    # no docker login
    default: false
  script:
    - cd docs/ && pip install -r requirements.txt && sphinx-build -M html . _build
  artifacts:
    paths:
      - docs/_build
  rules:
    - if: $CI_COMMIT_BRANCH == $RELEASE_BRANCH
      changes:
      - docs/**/*
    - if: $CI_COMMIT_BRANCH != $RELEASE_BRANCH
      changes:
      - docs/**/*


preview:docs:
  needs: ["build:docs"]
  stage: preview
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  inherit:
    # no docker login
    default: false
  script:
    - aws s3 rm s3://$AWS_PREVIEW_BUCKET/docs/$CI_COMMIT_SHORT_SHA/ --recursive
    - aws s3 cp docs/_build/html/ s3://$AWS_PREVIEW_BUCKET/docs/$CI_COMMIT_SHORT_SHA/ --recursive
    - echo "Done, docs available at https://$CI_COMMIT_SHORT_SHA--docs.$PREVIEW_DOMAIN/"
