# This workflow is to keep track of any open PRs and assure progress is being made.
# On abandoned PR, we make sure to close out the PR and notify the team.

# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.

name: Mark stale issues and pull requests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
  - cron: '0 0 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check PRs
      run: ../scripts/check-pr-age.sh
