name: Frontend CI

on:
  push:
    paths:
      - app/proto/**
      - app/web/**
      - deployment/frontend/**
      - .github/workflows/frontend.yml
      - .github/actions/**

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: [self-hosted, master]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-push-ecr
        with:
          module-name: web


  test-web:
    runs-on: [self-hosted, master]
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pre-tasks
      - working-directory: app/web
        run: |
          yarn install
          yarn test-ci

  test-web-prettier:
    runs-on: [self-hosted, master]
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pre-tasks
      - working-directory: app/web
        run: |
          yarn install
          yarn prettier --check *

  test-storybook:
    runs-on: [self-hosted, master]
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pre-tasks
      - working-directory: app/web
        run: |
          yarn install
          yarn build-storybook



  release:
    runs-on: [self-hosted, master]
    needs: [test-web, test-web-prettier, test-storybook]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/retag-release-ecr
        with:
          module-name: web


  deploy-dev:
    runs-on: [self-hosted, master]
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/helm-deploy
        with:
          module-name: frontend
          environment: dev

  deploy-staging:
    runs-on: [self-hosted, master]
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/helm-deploy
        with:
          module-name: frontend
          environment: staging
