export { default as CakeIcon } from "@material-ui/icons/CakeOutlined";
export { default as CouchIcon } from "@material-ui/icons/HotelOutlined";
export { default as EditIcon } from "@material-ui/icons/EditOutlined";
export { default as LanguageIcon } from "@material-ui/icons/LanguageOutlined";
export { default as LocationIcon } from "@material-ui/icons/LocationOnOutlined";
export { default as PersonIcon } from "@material-ui/icons/EmojiPeopleOutlined";
export { default as WorkIcon } from "@material-ui/icons/WorkOutlined";
export { default as DoneIcon } from "@material-ui/icons/Done";
export { default as CloseIcon } from "@material-ui/icons/Close";
